In [1]:
import pandas as pd
from cleaning.preprocess import getMissingValuesContainingColsWithCountOrMsg,handleMissingValues

In [2]:
titanic = pd.read_csv("datasets\\raw\\titanic.csv")
iris = pd.read_csv("datasets\\raw\\iris.csv")

In [3]:
titanic.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [4]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
getMissingValuesContainingColsWithCountOrMsg(titanic)

  Column Name  Missing Count
0         Age            177
1       Cabin            687
2    Embarked              2

In [6]:
getMissingValuesContainingColsWithCountOrMsg(iris)

'No Missing Values Containing Columns Found!'

In [7]:
handleMissingValues(titanic,{"Age" : "Drop Column"})

In [8]:
getMissingValuesContainingColsWithCountOrMsg(titanic)

  Column Name  Missing Count
0       Cabin            687
1    Embarked              2